services:
  - type: web
    name: science-experiment-advisor
    env: node
    buildCommand: cd Science-Experiment-Advisor-main && npm install
    startCommand: cd Science-Experiment-Advisor-main && npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: / 